"""add training_use column to master_games

Revision ID: 53c9846f6043
Revises: 5e4e147bdc96
Create Date: 2026-02-23 19:25:10.410457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53c9846f6043'
down_revision: Union[str, Sequence[str], None] = '5e4e147bdc96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_games', sa.Column('training_use', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master_games', 'training_use')
    # ### end Alembic commands ###
