"""add_master_games_table

Revision ID: 5e4e147bdc96
Revises: ae089b8c1674
Create Date: 2026-02-23 14:32:08.280366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e4e147bdc96'
down_revision: Union[str, Sequence[str], None] = 'ae089b8c1674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('white', sa.String(), nullable=False),
    sa.Column('black', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('white_elo', sa.Integer(), nullable=True),
    sa.Column('black_elo', sa.Integer(), nullable=True),
    sa.Column('eco', sa.String(), nullable=True),
    sa.Column('move_text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_games_black'), 'master_games', ['black'], unique=False)
    op.create_index(op.f('ix_master_games_eco'), 'master_games', ['eco'], unique=False)
    op.create_index(op.f('ix_master_games_event'), 'master_games', ['event'], unique=False)
    op.create_index(op.f('ix_master_games_result'), 'master_games', ['result'], unique=False)
    op.create_index(op.f('ix_master_games_white'), 'master_games', ['white'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_master_games_white'), table_name='master_games')
    op.drop_index(op.f('ix_master_games_result'), table_name='master_games')
    op.drop_index(op.f('ix_master_games_event'), table_name='master_games')
    op.drop_index(op.f('ix_master_games_eco'), table_name='master_games')
    op.drop_index(op.f('ix_master_games_black'), table_name='master_games')
    op.drop_table('master_games')
    # ### end Alembic commands ###
